Revert "[Tooling/Inclusion] Handle std::get symbol."
This reverts commit ebbd3935537e1c83cfebc461b7c2de25c0011e1d.

Causing many clangd test breakages, similar to:

error: no matching constructor for initialization of 'llvm::SmallVector<clang::tooling::stdlib::Header>'
                : llvm::SmallVector<clang::tooling::stdlib::Header>(
                  ^