Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit 4dba6b1c86927e2588577e9de10bb1f8a7f0084e.

It again broke builds on Windows:

  lldb/source/Host/common/HostNativeThreadBase.cpp(37,14): error:
  assigning to 'lldb::thread_result_t' (aka 'unsigned int') from
  incompatible type 'std::nullptr_t'