[flang][OpenMP] Remove pessimizing move introduced in 4df8adc350
This unbreaks the builders that diagnose this situation:

  error: moving a temporary object prevents copy elision [-Werror,-Wpess
imizing-move]
    341 |   static OmpClauseList empty{std::move(decltype(OmpClauseList:
:v){})};
        |                              ^