Revert "[clang] Implement Change scope of lambda trailing-return-type"
This reverts commit f84ba9695d5a5d240dcd75d282dac313692ba0d5.
This broke clang bootstrap: it made existing C++ code in LLVM invalid:

llvm/include/llvm/CodeGen/LiveInterval.h:630:53: error: captured variable 'Idx' cannot appear here
              [=](std::remove_reference_t<decltype(*Idx)> V,
                                                    ^