Revert "[runtimes] Add missing test dependencies to check-all (#72955)"
This caused some runtimes builds to fail with:
error: unknown target 'runtimes-test-depends'

See comments on the PR.

> The test-depends target contained all the dependencies needed to run the
> runtimes tests, but it was never added as a dependency of check-all.
> This caused some of the tsan tests to fail, since the custom libcxx
> build the tests were looking for was never built. Besides the tsan
> failures, this fixes all the other test failures I was seeing with:
> cmake -G Ninja -B release-build -S llvm \
>         -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
>         -DCMAKE_BUILD_TYPE=Release \
>         -DLLVM_ENABLE_ASSERTIONS=OFF \
>         -DLLVM_ENABLE_PROJECTS="clang;lld" \
>         -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind;compiler-rt"
>
> This is the same configuration the test-release.sh script uses, so I'm
> hoping this will also fix all the test failures we've been seeing when
> building the releases.
>
> Fixes #58680

This reverts commit 9ac342a91174a2ec105a01148a283c3a2109bd12.