Revert "[mlir][tosa] Split tosa-to-linalg named ops out of pass"
This reverts commit d5a17a5da47aed3d1b959f0f64e7394b7bb00966.

There is a missing CMake dependency, building with shared libraries is
broken:

55.509 [45/4/3061] Linking CXX shared library lib/libMLIRTosaToLinalg.so.14git
FAILED: lib/libMLIRTosaToLinalg.so.14git
...
TosaToLinalgPass.cpp: undefined reference to `mlir::createCanonicalizerPass()'