Revert "[MLIR][SPIRV] Start module combiner."
This reverts commit c10d9ba8f90ce9f4bfbc38e6c7846aef8cfaf96a.

Shared libs build is broken linking lib/libMLIRSPIRVModuleCombiner.so:

```
ModuleCombiner.cpp:
  undefined reference to `mlir::spirv::ModuleOp::addressing_model()
```

https://buildkite.com/mlir/mlir-core/builds/8988#e3d966b9-ea43-492e-a192-b28e71e9a15b