Fix build errors with a `LLVM_ENABLE_MODULES=ON` build (#107654)
The errors fixed were:
* llvm-project/llvm/include/llvm/Analysis/SyntheticCountsUtils.h:33:22:
error: missing '#include <__fwd/vector.h>'; default argument of 'vector'
must be defined before it is used
*
llvm-project/clang/include/clang/Tooling/Inclusions/StandardLibrary.h:41:15:
error: missing '#include <vector>'; 'vector' must be declared before it
is used
*
llvm-project/llvm/include/llvm/Transforms/InstCombine/InstCombiner.h:83:3:
error: missing '#include "llvm/ADT/PostOrderIterator.h"';
'ReversePostOrderTraversal' must be declared before it is used