Revert "Implement a new kind of Pass: dynamic pass pipeline"
This reverts commit 1458f7353d67aa0f4143f601104d2504de37ae39.

Test  mlir/test/Pass:dynamic-pipeline-fail-on-parent.mlir.test fails
when run with ASAN:

ERROR: AddressSanitizer: stack-use-after-scope on address ...

Reviewed By: bkramer, pifon2a

Differential Revision: https://reviews.llvm.org/D88079