[AArch64][ISel] Remove unused variable 'TRI' (NFC)
/Users/jiefu/llvm-project/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:6629:32: error: unused variable 'TRI' [-Werror,-Wunused-variable]
    const AArch64RegisterInfo *TRI = Subtarget->getRegisterInfo();
                               ^
1 error generated.