[libclang/python] Add missing concept declaration CursorKind (#69125)
Maps to
[`CXCursor_ConceptDecl`](https://github.com/llvm/llvm-project/blob/5f9efcde4ec60b5f53ec7afad2b4c8ffbbe3e659/clang/include/clang-c/Index.h#L2716),
added in 5f9efcde4ec60b5f53ec7afad2b4c8ffbbe3e659.

Without this I get this error on my codebase which uses C++20 concept
decls:
```
ValueError: Unknown template argument kind 604
```