[bazel] Add missing deps for #141864 (#142437)
Added in 0f4431f029bb18c7c64a6cfa60c3199130a83e6c.

```
external/llvm-project/llvm/include/llvm/Frontend/Driver/CodeGenOptions.h:16:10: error: module llvm-project//llvm:FrontendDriver does not depend on a module exporting 'llvm/Support/Compiler.h'
#include "llvm/Support/Compiler.h"
```