[mlir] Fix a warning
This patch fixes:

  mlir/lib/Transforms/Utils/DialectConversion.cpp:2104:9: error:
  unused variable 'rewriterImpl' [-Werror,-Wunused-variable]