[bazel][libc][NFC] Add missing layering deps (#107947)
After b5fc5d84ba18cf707e44b17c9753b8b4a71fd39e

e.g.

```
external/llvm-project/libc/test/src/math/smoke/NextTowardTest.h:12:10: error: module llvm-project//libc/test/src/math/smoke:nexttowardf_test does not depend on a module exporting 'src/__support/CPP/bit.h'
```