Revert "[llvm-exegesis] Add thread IDs to subprocess memory names (#84451)"
This reverts commit 240985a9e3693f529439aa8a5b17faed51f29c90.

This breaks building LLVM on macOS, failing with

    llvm/tools/llvm-exegesis/lib/SubprocessMemory.cpp:146:33: error: out-of-line definition of 'setupAuxiliaryMemoryInSubprocess' does not match any declaration in 'llvm::exegesis::SubprocessMemory'
    Expected<int> SubprocessMemory::setupAuxiliaryMemoryInSubprocess(