Revert "Move DroppedVariableStatsIRTest.cpp to CodeGen folder"
This reverts commit 6f26bc1b9623877ae81532454ac36b873bbdc5c7.

Revert "Reland 274166a361f2b31b4affa7b36b886b4e34b47ef1 (#119650)"

This reverts commit e78d169d26962f6803a02f8324f1b7b7a91d880a.

This is because the clang-ppc64le-linux-multistage bot breaks with error

undefined reference to `vtable for llvm::DroppedVariableStatsIR'