Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit efcb81bbd5150350fd8a7477cc9e1f829c7656a4.
Breaks building on Windows:

    ../../lldb/include\lldb/Host/HostNativeThreadBase.h(49,36): error:
        cannot initialize a member subobject of type 'lldb::thread_result_t'
        (aka 'unsigned int') with an rvalue of type 'std::nullptr_t'
      lldb::thread_result_t m_result = nullptr;
                                       ^~~~~~~
    1 error generated.