evert "[mlir] Limit Python dependency to Development.Module when possible."
This reverts commit feecf344f68f02d181ed31e840922715c650b123.

The build is broken with errors like:

GPUPasses.cpp:(.text.pybind11_object_init[pybind11_object_init]+0x118): undefined reference to `PyExc_TypeError'