Revert "[MLIR][Presburger] introduce SetCoalescer"
This reverts commit 5910c7f448acea34b2bbdcb694ea085d776eb002.

The build is broken with some configurations (gcc-5 and gcc-8):

mlir/lib/Analysis/Presburger/PresburgerRelation.cpp:402:32: error: qualified name does not name a class before '{' token
 class presburger::SetCoalescer {