Revert "Threading: Convert Optional to std::optional"
This reverts commit 8f44d3b9f038a004715470d98b783645023b39b5.

This commit breaks the build for BOLT:
  bolt/lib/Profile/DataAggregator.cpp:264:66: error: no viable
  conversion from 'Optional<StringRef>[3]' to
  'ArrayRef<std::optional<StringRef>>'