Revert "Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'"
This reverts commit da2e47bddfa03220931a01abbef0bdb667d0528b.

A bot is broken