Revert "[lldb] [gdb-remote client] Refactor handling qSupported"
This reverts commit 9ad2949bb2da3622a67315573349a64b83c19669.

It fails to build, with errors such as:
  GDBRemoteCommunicationClient.cpp:1005:20:
  error: no viable overloaded '='
          avail_name = compression;