Revert "[compiler-rt] Avoid memintrinsic calls inserted by the compiler"
This reverts commit 5cb233e0ea61d9df078d11d9c0e695779da49494.

Fails on Mac OS with "sanitizer_libc.cpp:109:5: error: aliases are not
supported on darwin".