[mlir] Fix build race condition in Pass Manager tests
That Linaro has been seeing on our dylib bot:
https://lab.llvm.org/staging/#/builders/171/builds/79

In file included from /home/tcwg-buildbot/worker/flang-aarch64-dylib/llvm-project/mlir/test/lib/Pass/TestPassManager.cpp:10:
/home/tcwg-buildbot/worker/flang-aarch64-dylib/llvm-project/mlir/test/lib/Pass/../Dialect/Test/TestOps.h:148:10: fatal error: 'TestOps.h.inc' file not found
  148 | #include "TestOps.h.inc"
      |          ^~~~~~~~~~~~~~~

Reported in https://github.com/llvm/llvm-project/issues/124335 and
https://github.com/llvm/llvm-project/issues/124485.

I think this was caused by https://github.com/llvm/llvm-project/pull/123910,
and so I've followed what https://github.com/llvm/llvm-project/pull/125004 did,
which seems to be a follow up to that. Same kind of error.

I was not able to reproduce the failure locally, but dylib and
normal builds are ok with this change so I will push it and monitor
the bot's results for a few days.