Revert "[lsan] On Fuchsia, don't use atexit hook for leak checks"
This reverts commit 05503cc5e1714ccd3f7bf1d4029f08d1f5d4f5f6.
This reverts commit 5e0ea7d60f65851491e4a5f98487ccb3a5eba2b7.

Causes linker errors which were not fixed by the subsequent commit
either:

/home/nikic/llvm-project/compiler-rt/lib/asan/asan_rtl.cpp:503: error: undefined reference to '__asan::InstallAtExitCheckLeaks()'