Revert "[lldb] Upstream support for Foundation constant classes"
This reverts commit 37bbabc069e7ea304b31c6fa9bd45fc50dc0572b.

This breaks build bots witha  missing file:
/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/source/Plugins/Language/ObjC/Cocoa.cpp:10:10: fatal error: 'objc/runtime.h' file not found