[BOLT] Fix a warning
This patch fixes:

  bolt/lib/Rewrite/DWARFRewriter.cpp:187:18: error: private field
  'Rewriter' is not used [-Werror,-Wunused-private-field]

Note that:

  commit a5505d6c822b64e85504d32dc465b8945f091e7b
  Author: Sayhaan Siddiqui <49014204+sayhaan@users.noreply.github.com>
  Date:   Mon Jun 10 10:46:20 2024 -0700

removed the last use of Rewriter.