Revert "Move DroppedVariableStats to CodeGen lib (#120650)"
This reverts commit 54e8d8b9944630e388b6664431c8f65682527f64.

Broke bot ppc64le-clang-multistage-test:

undefined reference to
`llvm::DroppedVariableStats::populateVarIDSetAndInlinedMap in
In function `llvm::DroppedVariableStatsIR::visitEveryInstruction