[lldb] Fix "NameError: name 'self' is not defined" when using crashlog -c
This fixes a regression introduced by 9a4058e3b1a3 that results in a
NameError: (name 'self' is not defined) when using crashlog with the -c
option.

rdar://110007391