Revert "[LLD] [COFF] Implement a GNU/ELF like -wrap option"
This reverts commit 49d4f95dab7c8ab6d27c8411a40668d111c4681e.

Breaks Windows builds.

C:\src\llvm-mint\lld\COFF\Symbols.cpp(26,1): error: static_assert failed due to requirement 'sizeof(lld::coff::SymbolUnion) <= 48' "symbols should be optimized for memory usage"
static_assert(sizeof(SymbolUnion) <= 48,