[symbolizer] Change error message if module not found (recommit)
This is a recommit of 863f989f57a9, reverted in 13f973c3593a, because
it caused compilation error in
compiler-rt/lib/sanitizer_common/symbolizer/sanitizer_symbolize.cpp.
The error was fixed by Kasimir Georgiev in 4b539097926d, but this
commit was reverted in 3eb0fffcf140, because the initial commit was
reverted.

This commit reverts both the reverting commits, 13f973c3593a and
3eb0fffcf140.

Original commit message is below.

If llvm-symbolize did not find module, the error looked like:

    LLVMSymbolizer: error reading file: No such file or directory

This message does not follow common practice: LLVMSymbolizer is not an
utility name. Also the message did not not contain the name of missed file.

With this change the error message looks differently:

    llvm-symbolizer: error: 'abc': No such file or directory

This format is closer to messages produced by other utilities and allow
proper coloring.

Differential Revision: https://reviews.llvm.org/D148032