Revert "[RISCV][NFC] Make generated intrinsic records more human-readable (#133710)"
This reverts commit f409ba4bb43acbe524a2775fe9301156f7f52594.

Error: "declaration of ‘clang::RISCV::RequiredExtensions
{anonymous}::SemaRecord::RequiredExtensions’ changes meaning of
‘RequiredExtensions’ [-fpermissive]"