Revert "Use-after-return sanitizer binary metadata"
This reverts commit cf9876b1247326235e0f6ab70fa7b83e89f112eb.

This patch results in:

  llvm/lib/CodeGen/SanitizerBinaryMetadata.cpp:57:17: error: no member
  named 'size' in 'llvm::MDTuple'