Revert "[llvm] add zstd to llvm::compression namespace"
This reverts commit 278ef0466feeec08088ff99c1753fddaec158ef0.

Breaks macOS builds with this:
llvm/lib/Support/Compression.cpp:24:10: fatal error: 'zstd.h' file not found