Revert "[lld-macho] Fix symbol relocs handling for compact unwind's functionAddress"
This reverts commit 810da58fcda8892e6c74844ad71b4e55bc77e393.

The commit in question causes:

  lld/MachO/InputFiles.cpp:916:13: error: use of undeclared identifier
  'it'