Revert "[ubsan] Simplify ubsan_GetStackTrace"
This reverts commit 537a896fa8049cd849a4158a5c7f99acb5b2a1bb.

I don't quite understand why, but this causes a linker error for
me and a number of buildbots:

/home/npopov/repos/llvm-project/compiler-rt/lib/ubsan/../sanitizer_common/sanitizer_stacktrace.h:130: error: undefined reference to '__sanitizer::BufferedStackTrace::UnwindImpl(unsigned long, unsigned long, void*, bool, unsigned int)'