Revert D130308 "[clang] extend getCommonSugaredType to merge sugar nodes"
This reverts commit a5a3460228ec80f403aa4468c24f15166b539739.
There are multiple complaints on the review.

In addition, it may cause spurious
```
error: invalid operands to binary expression ('SinkPrinter' and 'char[cluster_name_length]')
note: candidate template ignored: substitution failure: variably modified type 'char *' cannot be used as a template argument SinkPrinter operator<<(const SinkPrinter &s, T) {
```
for some C++ code