[SPIR-V] Add missing ScalarOpts library (#114384)
Fixes an "undefined reference to `llvm::createRegToMemWrapperPass()'"
linker error introduced by d00add4a9d2f ("[SPIR-V] Fix BB ordering &
register lifetime (#111026)", 2024-10-30).