Revert "[InferAttrs] Add writeonly to all the math functions"
This reverts commit 7163fa65e0c79640ed943a4867570742998fd6cb and
0ab349ac918c799468b31ddfcc84df9459df7459.

That commit caused crashes with compilation e.g. like this
(not fixed by the follow-up commit):

$ cat sqrt.c
float a;
b() { sqrt(a); }
$ clang -target x86_64-linux-gnu -c -O2 sqrt.c
Attributes 'readnone and writeonly' are incompatible!
  %sqrtf = tail call float @sqrtf(float %0) #1
in function b
fatal error: error in backend: Broken function found, compilation aborted!