Fix link error after 9f73548c30 with shared libraries
/usr/bin/ld: CMakeFiles/ProfileDataTests.dir/PGOCtxProfReaderWriterTest.cpp.o: undefined reference to symbol '_ZN4llvm15BitcodeAnalyzer7analyzeESt8optionalINS_13BCDumpOptionsEES1_INS_9StringRefEE'
/usr/bin/ld: /work/kparzysz/git/llvm.org/b/x86/lib/libLLVMBitReader.so.20.0git: error adding symbols: DSO missing from command line