Revert "lit: revert 134b103fc0f3a995d76398bf4b029d72bebe8162"
This reverts commit eb453e3c873b485f02d8ce188b0a76ec9bcd033c.

Causing messages like:

  File "...\Python\Python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 74