Revert "Fix attr docs from previous no-unique-adderss change (#67195)"
This reverts commit bc8a9aa89cd3ff2426888d71011db42d597f1059.

It caused
```
error: Record `NoUniqueAddress', field `Documentation' exists but does not have a list value
```