Revert "Add symbol locator time for each module in statistics (#134563)"
This reverts commit 298ca799209bf0315af9c34bbb03c4d4954b8596.

Multiple buildbot failures have been reported:
https://github.com/llvm/llvm-project/pull/134563

The build fails with:

  lldb/source/Target/Statistics.cpp:75:39: error: use of undeclared
  identifier 'num_symbols_loaded'