Revert "[mlir][ODS] Use StringLiteral instead of StringRef when applicable"
This reverts commit 555ffabb7a91f7b4fa7624c3a4018a36b16d6381 because
it breaks GCC 5 build:

  error: could not convert '(const char*)""' from 'const char*' to 'llvm::StringLiteral'
     static ::llvm::StringLiteral getDialectNamespace() { return ""; }