Revert "[clang-format] Add -j to clang-format-diff to speed up formatting"
This reverts commit 11ed0fb7976b4b552ec4df9e74816c926b39170a.

Makes clang_format_diff.py always fail with:

    Traceback (most recent call last):
      File "/home/npopov/repos/llvm-project/clang/tools/clang-format/clang-format-diff.py", line 177, in <module>
        main()
      File "/home/npopov/repos/llvm-project/clang/tools/clang-format/clang-format-diff.py", line 174, in main
        process_subprocess_result(proc, args)
      File "/home/npopov/repos/llvm-project/clang/tools/clang-format/clang-format-diff.py", line 42, in process_subprocess_result
        with open(filename) as f:
                  ^^^^^^^^
    NameError: name 'filename' is not defined