[MemProf] Include <ctime> to avoid MSVC failure (#114246)
My change in bb1ccb606d68213da3ac53b3c84025834a90edf4 added a call to
std::time which worked generally as there must be some transitive
include of <ctime>. However, I saw one MSVC bot failure:

InstrProfWriter.cpp(202): error C2039: 'time': is not a member of 'std'

from https://lab.llvm.org/buildbot/#/builders/63/builds/2325.

Presumably explictly including <ctime> should fix this.