Revert "[lld-macho] Avoid using bump-alloc in TrieBuider"
This reverts commit eeabf80c8dcb84513a051f62bd1c09ad2d5faa61.

That commit breaks the build with errors of the form:

/usr/local/google/home/saugustine/llvm/llvm-project/lld/MachO/ExportTrie.cpp:148:11: error: definition of implicitly declared destructor
TrieNode::~TrieNode() {